project_name: Napari Plywood Gallery
repository_url: https://github.com/kolibril13/plywood-gallery-napari
user_content_version: 0.4.15 (Napari)
description: |
  Cheat sheet gallery for napari
favicon: icon.png
preview_image: "thumbnail.png"
# https://raw.githubusercontent.com/kolibril13/plywood-gallery-napari/main/thumbnail.png
gallery_parameters_path: gallery_assets/gallery_parameters.json
